# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '16_pyqt5/96_tableview.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblProducts = QtWidgets.QTableWidget(self.centralwidget)
        self.tblProducts.setGeometry(QtCore.QRect(40, 30, 331, 351))
        self.tblProducts.setObjectName("tblProducts")
        self.tblProducts.setColumnCount(0)
        self.tblProducts.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(389, 29, 211, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.lineName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineName.setObjectName("lineName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineName)
        self.lblPrice = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblPrice.setObjectName("lblPrice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblPrice)
        self.linePrice = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.linePrice.setObjectName("linePrice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.linePrice)
        self.btnSave = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnSave)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblName.setText(_translate("MainWindow", "NAME : "))
        self.lblPrice.setText(_translate("MainWindow", "PRİCE :"))
        self.btnSave.setText(_translate("MainWindow", "SAVE"))
